dist: xenial
services: docker

before_install:
  - sudo apt-get update
  - sudo apt-get install -y qemu
  - wget https://releases.hashicorp.com/packer/1.4.0/packer_1.4.0_linux_amd64.zip -O packer.zip
  - unzip packer.zip
  - PACKER_LOG=1 ./packer build example.json
